Prevent elements of Select Language from touching notch
PalisadoesFoundation/talawa pull request #1081
Opened 2021-12-24 13:57 UTC by SriramPatibanda

**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1038 

**Did you add tests for your changes?**

N.A.

**Snapshots/Videos:**

N.A.

**If relevant, did you update the documentation?**

**Summary**

Since the edge parts of the app in the select language screen are unaccessible in devices without notch display, SafeArea has been wrapped around the scaffold.

**Does this PR introduce a breaking change?**

No

**Other information**

N.A.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

2021-12-26 06:06 UTC, CyberWake commented
@SriramPatibanda please provide an update on the issue why and when this happens since this issue is not just a matter of wrapping scaffold in the safearea widget.

2021-12-26 06:30 UTC, SriramPatibanda commented
> @SriramPatibanda please provide an update on the issue why and when this happens since this issue is not just a matter of wrapping scaffold in the safearea widget.

Sorry, I was away for a while. Yes, I'm trying to reproduce the issue again. I don't know the reason why it happened to me at that moment exactly but it did happen that size config wasn't initialized properly and hence I had opened the issue. I did try to reproduce it again but it isn't occurring to me now. But I'll drop a comment when it occurs to me again.

2021-12-26 07:52 UTC, CyberWake commented
The only case this happens is when you remove the particular code from splash screen. Else it shouldn't happen.

2021-12-29 09:21 UTC, CyberWake requested changes
Update needed on issue occurrence.

2021-12-29 15:30 UTC, SriramPatibanda commented
> The only case this happens is when you remove the particular code from splash screen. Else it shouldn't happen.

But I didn't touch that code at all. I didn't know why it happened. That's why I had tagged the mentors in the issue and asked if bounding it by safe area would be a better option and after being assigned, I implemented it and sent a PR.

2021-12-29 15:41 UTC, CyberWake commented
@SriramPatibanda the thing is this cannot be done in the manner since the UI is made with the figma designs with all the specific sizes hence we cannot use safearea at this point when it's not needed also the issue is not the improper rendering as per the issue stated the issue is the size config is not initializing. Please research more since the only case I told is the only way the issue arises. Please let me know if we can close this issue and PR if you don't find the issue reproducable.

2021-12-29 15:49 UTC, SriramPatibanda commented
> @SriramPatibanda the thing is this cannot be done in the manner since the UI is made with the figma designs with all the specific sizes hence we cannot use safearea at this point when it's not needed also the issue is not the improper rendering as per the issue stated the issue is the size config is not initializing. Please research more since the only case I told is the only way the issue arises. Please let me know if we can close this issue and PR if you don't find the issue reproducable.

Ok, I'll research more about it as you suggested. You can close the PR and issue and I'll report it if I reproduce it again.

2021-12-29 15:53 UTC, closed without merging