Fix #1371 In login screen , keyboard covering huge portion of UI
PalisadoesFoundation/talawa pull request #1375
Opened 2022-12-15 12:58 UTC by Tanmoy741127

**What kind of change does this PR introduce?**
This PR added an listener on Textfield FocusNode on login screen. When the textfield focused and keyboard apeared in screen, top margin will be reduced , when all the textfields unfocused or the keyboard disappeared the top margin will back to normal state.

**Issue Number:**

Fixes #1371 

**Did you add tests for your changes?**
That doesn't required test. Only UI changes. 

**Snapshots/Videos:**
Old UX
<img src="https://user-images.githubusercontent.com/57363826/207862412-14730238-99ae-4062-bc76-e8422c6dad14.png" width="200px"/>

New UX
https://user-images.githubusercontent.com/57363826/207862371-a45868c4-0075-418c-a74a-71b122af9248.mp4

**Summary**
This PR added an listener on Textfield FocusNode on login screen. When the Textfield focused and keyboard apeared in screen, top margin will be reduced , when all the textfields unfocused or the keyboard disappeared the top margin will back to normal state.

The container has been replaced with __AnimatedContainer__ to add animation while decreasing/increasing the top margin. 

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

2022-12-16 00:20 UTC, palisadoes requested changes
Please update the tests for the files you updated.

2022-12-16 00:39 UTC, palisadoes commented
Please fix the failing tests. You probably need to run the flutter formatter.

2022-12-16 02:01 UTC, Tanmoy741127 commented
@palisadoes code formatted and unit tests has been added

2022-12-16 05:09 UTC, SiddheshKukade requested changes

2022-12-16 06:00 UTC, Tanmoy741127 commented on test/widget_tests/pre_auth_screens/login_test.dart
> +    // When the password textfield is focused, the top margin is 0.01% of the screen height
fixed in latest commit

2022-12-16 06:00 UTC, Tanmoy741127 commented on test/widget_tests/pre_auth_screens/login_test.dart
> +    // When the email textfield is focused, the top margin is 0.01% of the screen height
fixed in latest commit

2022-12-16 10:55 UTC, Tanmoy741127 commented
@SiddheshKukade grammatical error fixed

2022-12-18 06:08 UTC, SiddheshKukade commented on test/widget_tests/pre_auth_screens/login_test.dart
> +    // When the textfields is not focused, the top margin is 0.2% of the screen height
This is not fixed

2022-12-19 15:23 UTC, JamaicanFriedChicken approved these changes

2022-12-19 15:59 UTC, Tanmoy741127 commented
@SiddheshKukade can you please review the changes ?

2022-12-25 07:34 UTC, closed without merging

2022-12-25 13:38 UTC, palisadoes commented
@Tanmoy741127 why did you close this?