Updated Installation.md by adding proper documentation regarding setting up the talawa app
PalisadoesFoundation/talawa pull request #1385
Opened 2023-01-14 05:18 UTC by AntoTomAbraham

Solved issue #1384

2023-01-14 13:26 UTC, palisadoes requested changes
Please make the requested updates. Refer to any uploaded images more specifically. We really need to have this documentation done correctly.

2023-01-14 13:26 UTC, palisadoes commented on INSTALLATION.md
> +1. You need to setup all the 3 projects locally ([talawa](https://github.com/PalisadoesFoundation/talawa/blob/develop/INSTALLATION.md), [talawa-api](https://github.com/PalisadoesFoundation/talawa-api
Please find a way to exclude links that include a specific branch. If the default branch changes, then the documentation will be incorrect.

2023-01-14 13:26 UTC, palisadoes commented on INSTALLATION.md
> +2. After setting up [talawa-api](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md) and [talawa-admin](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/
Please find a way to exclude links that include a specific branch. If the default branch changes, then the documentation will be incorrect.

2023-01-14 13:26 UTC, palisadoes commented on INSTALLATION.md
> +2. After setting up [talawa-api](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md) and [talawa-admin](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/
What type of account and why?

2023-01-14 13:26 UTC, palisadoes commented on INSTALLATION.md
> +3. After creating an account in talawa admin edit data in mongodb document under user collection by changing userType from ADMIN to SUPERADMIN and adminApproved from false to true
Why isn't this possible when creating an account? Do we need to update Talawa-Admin to allow this?

2023-01-14 13:26 UTC, palisadoes commented on INSTALLATION.md
> +4. After creating account, login and create an organisation in talawa-admin
Please be more specific, which account?

2023-01-15 06:07 UTC, AntoTomAbraham commented
I have made the necessary changes, please review the PR

2023-01-15 22:06 UTC, palisadoes approved these changes

2023-01-15 22:44 UTC, merged