Add test for chat_list_tile_data_model.dart
PalisadoesFoundation/talawa pull request #1433
Opened 2023-01-27 14:32 UTC by droy312

**What kind of change does this PR introduce?**

Adds test for lib/models/chats/chat_list_tile_data_model.dart

**Issue Number:**

Fixes #1427 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-01-27 18:34 UTC, noman2002 commented
As the codecov is not getting triggered please attach a screenshot of code coverage to get this PR approved. It will be easier for mentors to review.

2023-01-27 21:36 UTC, noman2002 requested changes
Please try to get the coverage up to 100% for  chat_list_tile_data.model.dart. currently its at 75% .

2023-01-28 19:53 UTC, noman2002 commented
@droy312 please don't remove reviewers. They are assigned by organization members.

2023-01-28 19:54 UTC, noman2002 approved these changes

2023-01-28 22:43 UTC, palisadoes approved these changes

2023-01-28 22:44 UTC, merged