Fixes #1236 Create tests for organization_feed.dart
PalisadoesFoundation/talawa pull request #1478
Opened 2023-02-09 11:28 UTC by Ayush0Chaudhary

**What kind of change does this PR introduce?**
[Fixes](https://github.com/PalisadoesFoundation/talawa/commit/52a881a4f64531171c982247e525f7ece9e2c91d) https://github.com/PalisadoesFoundation/talawa/issues/1236 [Create tests for organization_feed.dart](https://github.com/PalisadoesFoundation/talawa/commit/52a881a4f64531171c982247e525f7ece9e2c91d)

**Issue Number:**

Fixes #1236

**Did you add tests for your changes?**

**Summary**
[Fixes](https://github.com/PalisadoesFoundation/talawa/commit/52a881a4f64531171c982247e525f7ece9e2c91d) https://github.com/PalisadoesFoundation/talawa/issues/1236 [Create tests for organization_feed.dart](https://github.com/PalisadoesFoundation/talawa/commit/52a881a4f64531171c982247e525f7ece9e2c91d)

**Does this PR introduce a breaking change?**
NO

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
YES

2023-02-09 12:17 UTC, Ayush0Chaudhary commented
I achieved **86.5%** coverage

![Screenshot from 2023-02-09 17-44-20](https://user-images.githubusercontent.com/95746190/217810211-b031f74a-d0f1-4372-a2cb-9f3bc188abb4.png)

Screen Shot for uncovered part
![Screenshot from 2023-02-09 17-46-17](https://user-images.githubusercontent.com/95746190/217810522-0733d25e-14f4-494f-bb5a-5c504bf47eaa.png)

@palisadoes @noman2002 @TheHazeEffect

2023-02-09 13:52 UTC, literalEval commented
@Ayush0Chaudhary do you need help in getting to 100% ?

2023-02-09 15:23 UTC, palisadoes commented
1. We are going to have delay any potential merge until this PR is complete https://github.com/PalisadoesFoundation/talawa/pull/1474
1. It may cause minor merge conflicts, so be prepared

2023-02-09 17:59 UTC, noman2002 requested changes
Please try to get it to 100%

2023-02-10 18:12 UTC, palisadoes commented
Please fix the linting error

2023-02-10 18:37 UTC, Ayush0Chaudhary commented
@noman2002 I was not able to mock stream and and I tried other methods, but was unsuccessful.

2023-02-10 18:43 UTC, Ayush0Chaudhary commented
@noman2002 @TheHazeEffect please review!

2023-02-11 18:27 UTC, noman2002 commented
@Ayush0Chaudhary Please don't remove reviewers, it is assigned for a purpose. Please refrain from these type of practice.

2023-02-11 18:28 UTC, noman2002 commented
> @noman2002 I was not able to mock stream and and I tried other methods, but was unsuccessful.

You can take help from @literalEval

2023-02-11 19:37 UTC, palisadoes commented
> @Ayush0Chaudhary Please don't remove reviewers, it is assigned for a purpose. Please refrain from these type of practice.

I 100% agree. Our volunteers have conflicting priorities and may not always be available on demand, but we are all trying to improve the code base.

2023-02-11 20:40 UTC, Ayush0Chaudhary commented
Sorry @palisadoes @noman2002 
I tried to ask for re review from Noman and clicked the red icon.

That led to removal of @TheHazeEffect review

It won't happen again, it was not intentional.

2023-02-11 20:41 UTC, palisadoes commented
> Sorry @palisadoes @noman2002 I tried to ask for re review from Noman and clicked the red icon.
> 
> That led to removal of @TheHazeEffect review
> 
> It won't happen again, it was not intentional.

Thanks

2023-02-11 21:58 UTC, noman2002 requested changes

2023-02-11 21:58 UTC, noman2002 commented on lib/view_model/after_auth_view_models/event_view_models/create_event_view_model.dart
> +    print(_image);
Remove print command.

2023-02-11 21:58 UTC, noman2002 commented on lib/view_model/after_auth_view_models/feed_view_models/organization_feed_view_model.dart
> +    print(_posts);
remove print

2023-02-11 21:58 UTC, noman2002 commented on test/widget_tests/after_auth_screens/feed/organization_feed_test.dart
> +}
remove these commented code.

2023-02-12 22:26 UTC, Ayush0Chaudhary commented
@noman2002 @palisadoes made the suggested changes.

2023-02-13 20:50 UTC, noman2002 approved these changes
Merge this but let the issue be open.

2023-02-13 21:23 UTC, palisadoes approved these changes

2023-02-13 21:24 UTC, palisadoes approved these changes

2023-02-13 21:24 UTC, merged