Fix Top Bar Overflow #1561
PalisadoesFoundation/talawa pull request #1576
Opened 2023-02-27 04:56 UTC by mmjsmohit

**What kind of change does this PR introduce?**
Fixes overflow issue on top bar in `explore_events.dart`

**Issue Number:**

Fixes #1561 

**Did you add tests for your changes?**
Yes, added a widget test in `explore_events_test.dart` named `Testing if the top bar overflows`

**Snapshots/Videos:**

![photo_2023-02-25_11-18-31](https://user-images.githubusercontent.com/65406090/221357061-1be4232e-30b5-4460-a553-c7e8117d7ca3.jpg)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
Yes

2023-02-27 21:49 UTC, palisadoes commented
Please fix the failing tests

2023-02-28 04:27 UTC, mmjsmohit commented
Can this PR be reviewed now? @palisadoes @noman2002 @TheHazeEffect

2023-02-28 15:45 UTC, noman2002 requested changes

2023-02-28 15:45 UTC, noman2002 commented on lib/views/after_auth_screens/events/explore_events.dart
> +                                scrollDirection: Axis.horizontal,
Remove this. We don't want it to be scrollable.

2023-03-05 13:34 UTC, Ayush0Chaudhary commented
@noman2002 @palisadoes can i continue this, if @mmjsmohit is not working on this anymore

2023-03-05 13:39 UTC, palisadoes commented
@mmjsmohit Are you still working on this. Please respond within the next day or we will close the PR and remove your assignment from the issue

2023-03-05 13:46 UTC, mmjsmohit commented
Yes I am working on this. Will try to make a new commit tomorrow.

2023-03-08 04:17 UTC, palisadoes commented
We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

2023-03-10 07:53 UTC, literalEval commented
@mmjsmohit try merging latest talawa/develop into your branch. That will fix the failing test case.

2023-03-11 16:25 UTC, noman2002 commented
@mmjsmohit Any progress ?

2023-03-11 16:48 UTC, closed without merging