Add test for Edit Task Page to validate onSave callback.
PalisadoesFoundation/talawa pull request #1613
Opened 2023-03-05 09:03 UTC by ikjot-2605

**What kind of change does this PR introduce?**

Introduces a new test for `lib/views/after_auth_screens/tasks/edit_task_page.dart` to test the `onSave()` callback.

**Issue Number:**

Fixes #1401 

**Did you add tests for your changes?**

Yes, this is a test related PR.

**Snapshots/Videos:**

![image](https://user-images.githubusercontent.com/55295613/222951453-c42fc6f9-8d79-4710-9a24-edffcdb33867.png)

**If relevant, did you update the documentation?**

N/A

**Does this PR introduce a breaking change?**

No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-06 05:14 UTC, CyberWake requested changes
@ikjot-2605 please add the test for on click events and on save for TaskForm widget. For Task form widget to invoke on save you can use the form key to invoke the onSave method in test. Similarly you can also write test for the on click event on text button

2023-03-06 05:43 UTC, TheHazeEffect submitted a review, later dismissed

2023-03-06 05:48 UTC, ikjot-2605 commented
> @ikjot-2605 please add the test for on click events and on save for TaskForm widget. For Task form widget to invoke on save you can use the form key to invoke the onSave method in test. Similarly you can also write test for the on click event on text button

Hi @CyberWake, this issue was specific to testing the edit_tasks_page.dart, and I've tested the onSave callback that it provides in the new test that I've added. 

Adding tests for task_form.dart is another issue that needs to be worked on, possibly in another MR for the sake of atomicity of commits.

2023-03-06 05:49 UTC, ikjot-2605 commented
> > @ikjot-2605 please add the test for on click events and on save for TaskForm widget. For Task form widget to invoke on save you can use the form key to invoke the onSave method in test. Similarly you can also write test for the on click event on text button
> 
> Hi @CyberWake, this issue was specific to testing the edit_tasks_page.dart, and I've tested the onSave callback that it provides(to the TaskForm) in the new test that I've added. 
> 
> Adding tests for task_form.dart is another issue that needs to be worked on, possibly in another MR for the sake of atomicity of commits.

2023-03-07 04:54 UTC, ikjot-2605 commented
> > @ikjot-2605 please add the test for on click events and on save for TaskForm widget. For Task form widget to invoke on save you can use the form key to invoke the onSave method in test. Similarly you can also write test for the on click event on text button
> 
> Hi @CyberWake, this issue was specific to testing the edit_tasks_page.dart, and I've tested the onSave callback that it provides(to the TaskForm) in the new test that I've added. 
> 
> Adding tests for task_form.dart is another issue(#1397) that needs to be worked on, possibly in another MR for the sake of atomicity of commits.
> 
> Please let me know if I've understood something incorrectly.

@CyberWake should I add tests for the task form as well in this MR?

2023-03-07 18:57 UTC, noman2002 approved these changes

2023-03-07 19:02 UTC, palisadoes approved these changes

2023-03-07 19:02 UTC, merged