Ignoring file that are generated during talawa testing and firebase initialization closes 1573
PalisadoesFoundation/talawa pull request #1632
Opened 2023-03-07 08:17 UTC by SiddheshKukade

**What kind of change does this PR introduce?**

Chore/Bugfix

**Issue Number:**

Fixes #1573

**Did you add tests for your changes?**

Not required.

**Snapshots/Videos:**

![image](https://user-images.githubusercontent.com/65951872/223362758-1407c7a0-957d-4a64-b83c-573c5da3442a.png)

**Summary**
These two files we're getting generated after running the `flutter test` command 
1. The `genhtml.perl` file contains current code coverage and due to that it is not relevant to merge it into the repository.
![image](https://user-images.githubusercontent.com/65951872/223363079-e44dcf8b-cec5-4549-89be-9667629364c6.png)
2. The ` test_img.png ` is a image generate to test some features of the app. Hence it is also not relevant to merge.
![image](https://user-images.githubusercontent.com/65951872/223363217-35dce6dc-c9c8-4f30-97f0-7911ea292e30.png)

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-07 08:32 UTC, SiddheshKukade commented
The code is ready to be reviewed.

2023-03-07 13:34 UTC, palisadoes commented
What about `firebase_options.dart` does that need to be included?

2023-03-08 04:16 UTC, palisadoes commented
We have a new check in place. All Talawa mobile app methods, classes and functions need to have suitable comments. Please refer to this issue as  reference for what is now required. The aim is to help us improve the quality of our automated documentation on docs.talawa.io.
 
- https://github.com/PalisadoesFoundation/talawa/issues/1479

To fix this issue:

1. You will be required to remove a line containing `ignore_for_file`
1. After doing so you'll be requested to update the comments appropriately

We have also tried to make the documentation step automatically update your IDE with a custom Linter. If you have any comments, please contact @literalEval who worked on this code.

2023-03-08 12:37 UTC, SiddheshKukade commented
> What about `firebase_options.dart` does that need to be included?

Sir for giving notifications to user which were added in #1327  we require that `firebase_options.dart`  file
But what I had observed previously was when new contributors were setting up their project they did not setup the firebase project and due to that the app causes a build err with the message that `firebaseOptions is not defined`
to solve that they  just comment out those functions (to get the app running) and add that commented code in PR without even noticing it. So I think adding a try catch at `main.dart` could prevent this from happening.

```dart
  try {
    if (urlBox.get('url') != null) {
      await setUpFirebaseKeys();

      await setUpFirebase();
      await setUpFirebaseMessaging();
    }
  } catch (e) {
    print("Firebase not working");
  }
```
Commit  : https://github.com/PalisadoesFoundation/talawa/pull/1632/commits/1a4934ece63a60a9e1a21da7c04b91c2b7ff8817

2023-03-08 12:38 UTC, SiddheshKukade commented
This check fails due to change in `main.dart` file and can be ignored here.
![image](https://user-images.githubusercontent.com/65951872/223715405-f8f56197-97fe-4928-9ad8-0e1f49d6ab6e.png)

2023-03-08 12:40 UTC, literalEval commented
@SiddheshKukade which branch do you use for pushing new commits ? I observed that all of your PRs tend to have the same list of commits, that too in large number. Please fix that.

2023-03-08 15:33 UTC, palisadoes commented
@SiddheshKukade  rebase your repo to the latest merge. The commit list is too long and distracting.

2023-03-11 16:55 UTC, noman2002 requested changes
add documentation in main.dart

2023-03-12 05:49 UTC, SiddheshKukade commented on lib/main.dart
>    }
try catch added to avoid the firebase errors during the initial build.

2023-03-12 05:49 UTC, SiddheshKukade commented on lib/main.dart
> +  ///
Needed to add the extra `\n /// ` to follow the docs lint rules

2023-03-12 10:47 UTC, literalEval commented
@SiddheshKukade can you revert your changes in `talawa_good_doc`? I have done these changes in my branch for `further enhancing talawa_lint`, along with other changes. I appreciate your effort in fixing this nasty bug, but it will be great if `talawa_lint` related changes are done in a separate and dedicated place, so that analysis of them, later on, can be easier. Thanks :)

2023-03-12 10:55 UTC, literalEval commented
Also, you can run `flutter pub run custom_lint` locally to check for analysis on your machine. You don't need to commit to check for it. If you need help in setting up `talawa_lint`, then I'm here to help :)

2023-03-12 11:06 UTC, SiddheshKukade commented
> 



> Also, you can run `flutter pub run custom_lint` locally to check for analysis on your machine. You don't need to commit to check for it. If you need help in setting up `talawa_lint`, then I'm here to help :)

@literalEval I know that.

The custom_lint was throwing errors for null type checking 
![image](https://user-images.githubusercontent.com/65951872/224531186-092af414-d2d7-4edd-99db-969450fc96cd.png)
So I've tried to fix them with some type checking 


But now it is still giving and unclear error of  `/// None` as you can see here. I've already added `/// None ` but it still gives error about it.
![image](https://user-images.githubusercontent.com/65951872/224540478-e913819e-093b-41d9-832c-2275e729d940.png)

2023-03-12 11:07 UTC, literalEval commented
> > 
> 
> > Also, you can run `flutter pub run custom_lint` locally to check for analysis on your machine. You don't need to commit to check for it. If you need help in setting up `talawa_lint`, then I'm here to help :)
> 
> @literalEval I know that.
> 
> The custom_lint was throwing errors for null type checking ![image](https://user-images.githubusercontent.com/65951872/224531186-092af414-d2d7-4edd-99db-969450fc96cd.png) So I've tried to fix them with some type checking
> 
> But now it is still giving and unclear error of `/// None` as you can see here. I've already added `/// None ` but it still gives error about it. ![image](https://user-images.githubusercontent.com/65951872/224540478-e913819e-093b-41d9-832c-2275e729d940.png)

Add explicit `void` type to that function. It will work :)

2023-03-12 11:08 UTC, literalEval commented
Plese confirm if it does :)

2023-03-12 11:10 UTC, palisadoes commented
> Plese confirm if it does :)

Does the script output say that the explicit void is required? If not, it needs to be updated.

2023-03-12 11:11 UTC, SiddheshKukade commented
It worked for that,
And what should be done here ? 
![image](https://user-images.githubusercontent.com/65951872/224540811-641376f9-3789-4642-b735-bc7e2b555be9.png)

2023-03-12 11:13 UTC, SiddheshKukade commented
> Does the script output say that the explicit void is required? If not, it needs to be updated.
It does not but adding that up would have save me a lot of time debugging. lol

2023-03-12 11:15 UTC, literalEval commented
> > Plese confirm if it does :)
> 
> Does the script output say that the explicit void is required? If not, it needs to be updated.

In my fix list :)

2023-03-12 11:17 UTC, literalEval commented
> > Does the script output say that the explicit void is required? If not, it needs to be updated.
> 
> It does not but adding that up would have been helped save to me a lot of hours debugging. lol

You could have just asked me :)

2023-03-12 11:24 UTC, SiddheshKukade commented
@literalEval  It is also not working for the getter functions.
![image](https://user-images.githubusercontent.com/65951872/224541351-fa3d374d-418d-43c0-b2b9-cf3de680c7cf.png)
![image](https://user-images.githubusercontent.com/65951872/224541361-19642f3a-c76b-4cff-ad09-ca9f6fee922f.png)

2023-03-12 11:25 UTC, literalEval commented
> @literalEval It is also not working for the getter functions. ![image](https://user-images.githubusercontent.com/65951872/224541351-fa3d374d-418d-43c0-b2b9-cf3de680c7cf.png) ![image](https://user-images.githubusercontent.com/65951872/224541361-19642f3a-c76b-4cff-ad09-ca9f6fee922f.png)

It is working :)
A getter returns something. It's not void.
Set the return type to `String` instead of None :)

2023-03-12 11:29 UTC, literalEval commented
I am also thinking to exclude getters and setters from `function/method` type, as the argument and return types are obvious.

2023-03-12 11:37 UTC, literalEval commented
@SiddheshKukade that would be `Future<void>` and not void :)
And so will be the 
```
/// returns:
/// * `Future<void>`: ...

2023-03-12 11:58 UTC, literalEval commented
> @SiddheshKukade can you revert your changes in `talawa_good_doc`? I have done these changes in my branch for `further enhancing talawa_lint`, along with other changes. I appreciate your effort in fixing this nasty bug, but it will be great if `talawa_lint` related changes are done in a separate and dedicated place, so that analysis of them, later on, can be easier. Thanks :)

@SiddheshKukade :)

2023-03-12 11:59 UTC, SiddheshKukade commented
@noman2002, the code is ready to be reviewed. 
This error can be ignored as it is caused due to change in `.gitignore` file.
![image](https://user-images.githubusercontent.com/65951872/224543125-f6ccb9f4-67f4-4218-accd-ca69a1a2e188.png)

2023-03-12 12:02 UTC, palisadoes commented
@literalEval Create an issue to update the script

2023-03-12 12:03 UTC, SiddheshKukade commented
> > @SiddheshKukade can you revert your changes in `talawa_good_doc`? I have done these changes in my branch for `further enhancing talawa_lint`, along with other changes. I appreciate your effort in fixing this nasty bug, but it will be great if `talawa_lint` related changes are done in a separate and dedicated place, so that analysis of them, later on, can be easier. Thanks :)
> 
> @SiddheshKukade :)

Hello @literalEval, I've created an issue to keep report of this now.

2023-03-12 12:09 UTC, literalEval commented
@SiddheshKukade works. Thanks.

2023-03-13 13:32 UTC, SiddheshKukade commented
@noman2002, @TheHazeEffect, @tonythegr8 please review.

2023-03-13 18:06 UTC, palisadoes approved these changes

2023-03-13 18:08 UTC, merged