Fix Edit Event Routing
PalisadoesFoundation/talawa pull request #1642
Opened 2023-03-08 16:08 UTC by ikjot-2605

**What kind of change does this PR introduce?**

This PR introduces the fix for the edit event flow. Currently, on pressing the "Done" button in the edit event page, we are shown a loader momentarily and are kept on the same page - with a `Null check operator used on a null value` in the background(due to the null arguments in the Main Screen route). After this PR, the users will be redirected to the events page.

**Issue Number:**

Fixes #1614 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Before:

https://user-images.githubusercontent.com/55295613/223220112-7bdf5e0d-5e9d-4905-b407-ab9fe1d4aea2.mp4

After:

https://user-images.githubusercontent.com/55295613/223222224-55d18aca-5504-4c57-bbcd-186a13be7ec0.mp4

**If relevant, did you update the documentation?**

N/A

**Does this PR introduce a breaking change?**

No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-08 16:38 UTC, ikjot-2605 commented
@literalEval could you look at why the custom lint check is failing for this PR?
At the moment it shows just one issue with a return type where it expects a `void`, but the actual function returns Stream<Event>.

2023-03-08 16:40 UTC, ikjot-2605 commented
Also, @palisadoes - I had to create a new MR because I had some issues while rebasing in the previous one.

Apologies for the inconvenience.

2023-03-08 16:42 UTC, literalEval commented
@ikjot-2605 I'll look into the issue and update you. Thanks.

2023-03-08 16:49 UTC, literalEval commented
@ikjot-2605 I am trying my best to resolve queries regarding the custom lint rules and will create a proper documentation for it as soon as possible. Please bear with me for some time. Thanks for your patience.

2023-03-08 16:58 UTC, ikjot-2605 commented
> @ikjot-2605 I am trying my best to resolve queries regarding the custom lint rules and will create a proper documentation for it as soon as possible. Please bear with me for some time. Thanks for your patience.

That's great, the work done on this lint checking is absolutely fabulous by the way. Kudos @literalEval!!

2023-03-08 17:36 UTC, noman2002 requested changes
Get the coverage of event service to 100%

2023-03-08 17:39 UTC, ikjot-2605 commented
> Get the coverage of event service to 100%

Hi, there's a separate issue #1531 for adding event_service tests, which is currently assigned to someone else. 

How should I proceed?

2023-03-08 17:46 UTC, palisadoes commented
> > Get the coverage of event service to 100%
> 
> Hi, there's a separate issue #1531 for adding event_service tests, which is currently assigned to someone else.
> 
> How should I proceed?
> 
> @noman2002

OK, let's work with this PR as is.

2023-03-09 04:55 UTC, ANUKULJHA1506 commented
@ikjot-2605  if you want to work on the issue #1531  we can work on it together , I have  written some test code for event_service.dart file but it is not complete .

2023-03-09 12:29 UTC, palisadoes approved these changes

2023-03-09 12:29 UTC, merged