Improved testing select_contact
PalisadoesFoundation/talawa pull request #1645
Opened 2023-03-09 20:51 UTC by Kraken005

**What kind of change does this PR introduce?**

This PR improves the testing of select_contact.dart file.

**Issue Number:**
#1520 

Fixes #1520 
**Did you add tests for your changes?**

Yes. I added test for title display.

**Summary**

A new widget testing for title display. It would overall increase the testing code coverage.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-10 02:46 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

- The overall code coverage drops below the target threshold of the repository
- Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

2023-03-10 02:46 UTC, Cioppolo14 commented
@Kraken005 Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

The overall code coverage drops below the target threshold of the repository
Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

2023-03-11 16:58 UTC, noman2002 requested changes
fix the formatting and why there is change in pubspec.lock ?

2023-03-20 18:50 UTC, noman2002 commented
@Kraken005 Any progress on this one ??

2023-03-20 18:51 UTC, noman2002 commented on .github/workflows/codecov.yml
> +
Why a new workflow is added?

2023-03-21 19:44 UTC, Kraken005 commented
The code base testing failed at /home/runner/work/talawa/talawa/test/widget_tests/widgets/task_schedule_test.dart.

2023-03-24 19:23 UTC, noman2002 commented
Please add documentation for the changes you have made

2023-03-30 16:04 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

2023-04-02 17:51 UTC, noman2002 requested changes
Please fix the failing test.

2023-04-13 01:22 UTC, palisadoes commented
closing due to a inactivity

2023-04-13 01:22 UTC, closed without merging