[GSoC]Feature request: Add Hashtag feature for a post
PalisadoesFoundation/talawa pull request #2051
Opened 2023-10-11 16:38 UTC by Ayush0Chaudhary

**What kind of change does this PR introduce?**
add the tag feature

**Issue Number:**

Fixes #2050

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**
yes

2023-10-12 07:05 UTC, noman2002 requested changes
Fix the failing test.

2023-10-19 05:50 UTC, noman2002 approved these changes

2023-10-26 13:12 UTC, Ayush0Chaudhary commented
@palisadoes

2023-10-27 05:53 UTC, noman2002 approved these changes

2023-10-27 18:21 UTC, palisadoes approved these changes

2023-10-27 18:21 UTC, merged