Unittest for pinned_post.dart
PalisadoesFoundation/talawa pull request #2178
Opened 2023-11-29 12:26 UTC by nidhin29

This change included the Unittest for pinned post

Issue Number: https://github.com/PalisadoesFoundation/talawa/issues/2161

Fixed https://github.com/PalisadoesFoundation/talawa/issues/2161

Did you add tests for your changes?

Yes

Summary

It is unittest for pinned_post.

Does this PR introduce a breaking change?

No, this does not introduce any major changes to the codebase.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?

Yes, i have followed the guidelines.

2023-11-29 12:55 UTC, nidhin29 commented
@noman2002 The pinned post are manually passed so is it possible to check the error cases

2023-11-29 13:14 UTC, nidhin29 commented
@noman2002  Sir,I have written tests for other lines if it is possible to test the error case pls tell me and I will work on it

2023-12-01 05:45 UTC, noman2002 requested changes

2023-12-01 05:45 UTC, noman2002 commented on lib/widgets/pinned_post.dart
> +                            ),
Please write the test for this error widget.

2023-12-01 05:47 UTC, noman2002 commented
> tests for other lines if it

Yes, Please write the test for error widget. You can mock the situation by giving incorrect image url.

2023-12-03 10:09 UTC, closed without merging