Enhancing UI for inviting
PalisadoesFoundation/talawa pull request #2229
Opened 2023-12-09 17:48 UTC by Dante291

**What kind of change does this PR introduce?**

Enhancing UI for inviting other users to join an organization using QR.

**Issue Number:**

Fixes #2189 

**Did you add tests for your changes?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-09 17:50 UTC, Dante291 commented
@palisadoes Sorry for closing PR I was having some trouble to resolve conflicts and with formatting, this one is after latest pull could you please assign reviewers.

2023-12-09 17:53 UTC, Dante291 commented
Before: 

![Screenshot_1701450473](https://github.com/PalisadoesFoundation/talawa/assets/103507835/19bd999b-9254-48ad-886f-2f5642407888)

after:

![Screenshot_1701880428](https://github.com/PalisadoesFoundation/talawa/assets/103507835/19102128-3c3f-4ca6-9ef7-8004dda4e8be)

2023-12-09 18:10 UTC, palisadoes commented
Please try to get your code coverage up to 100% on the edited file

2023-12-13 05:58 UTC, noman2002 requested changes

2023-12-13 05:58 UTC, noman2002 commented on lib/view_model/after_auth_view_models/profile_view_models/profile_page_view_model.dart
> +                ),
Please write the test for these lines.

2023-12-13 16:36 UTC, Dante291 commented
Translation is working fine:
![Screenshot_1702485306](https://github.com/PalisadoesFoundation/talawa/assets/103507835/ead636db-1cb1-4716-a91c-dd2a7b81efd5)

2023-12-13 16:38 UTC, Dante291 commented
@palisadoes @noman2002 I added test for every method except logout because @Azad99-9 has did some modification to that method and also have written test for it in this [PR.](https://github.com/PalisadoesFoundation/talawa/pull/2227)

2023-12-14 05:51 UTC, noman2002 approved these changes
Looks good, Thank you.

2023-12-14 12:22 UTC, palisadoes approved these changes

2023-12-14 12:24 UTC, merged