Unit test for services post_services.dart
PalisadoesFoundation/talawa pull request #2244
Opened 2023-12-12 16:52 UTC by PraminBudhathoki

What kind of change does this PR introduce?

This change included the Unit test for service post_service.dart

Issue Number:https://github.com/PalisadoesFoundation/talawa/issues/2160

Fixes https://github.com/PalisadoesFoundation/talawa/issues/2160

Did you add tests for your changes?

Yes, I have added tests.

Does this PR introduce a breaking change?

No, this does not involve major changes to the codebase.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?

Yes, I have followed the contribution guideline.

2023-12-13 05:56 UTC, noman2002 requested changes
Please fix the failing tests.

2023-12-14 11:15 UTC, Dante291 commented
Hello @PraminBudhathoki, there are certain linting checks in Talwa in order to maintain the proper code format so that the good practice of writing code in a proper formatted way such that it should be understandable by all the current and future contributors remains maintained.

 `// ignore_for_file: talawa_api_doc, avoid_dynamic_calls // ignore_for_file: talawa_good_doc_comments` these lines basically ignore these checks, but what you could do is write proper documentation for each method written in that file and give a correct Data type to the objects/variables that are declared as `Dynamic`. 
 
 You could get the proper doc format for the methods which shows linting errors by pressing` Ctrl+. ` and then write the proper doc for the required function.
 
 I hope this helped you a little, do hit me up or in #talawa-mobile channel on slack if you need any further help.

2023-12-15 05:45 UTC, noman2002 approved these changes

2023-12-15 05:48 UTC, palisadoes approved these changes

2023-12-15 05:48 UTC, merged