Feature request: Enhancing UX by introducing User Profile Modification Feature
PalisadoesFoundation/talawa pull request #2268
Opened 2023-12-24 07:01 UTC by Dante291

**What kind of change does this PR introduce?**

Introducing user profile modification feature where user would be able to customize their profile.

**Issue Number:**

Fixes #2261 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-24 15:38 UTC, Dante291 commented
Made profile pic visible at other screens of the app too:

![Screenshot_1703412506](https://github.com/PalisadoesFoundation/talawa/assets/103507835/f5a03c92-da05-4824-a130-0fdbbd9dd5bb)


![Screenshot_1703412514](https://github.com/PalisadoesFoundation/talawa/assets/103507835/933a7cc4-e436-490a-97ca-f69c64676b67)

2023-12-24 15:40 UTC, Dante291 commented
@noman2002 @Cioppolo14 @Kevoniat Please assign reviewers for this, thanks.

2023-12-25 15:34 UTC, literalEval requested changes
1. Remove print statements.
2. Write good documentation. Don't leave the template as is.
3. Add empty lines to make the code more readable.

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/add_post_view_models/add_post_view_model.dart
> +  String? get userName =>
Why mark this optional ?

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/add_post_view_models/add_post_view_model.dart
> +  /// more_info_if_required
Remove the 2nd and 3rd line. Please read Dart documentation guidelines once.

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart
> +  /// more_info_if_required
Remove this line.

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart
> +  /// * `firstName`: define_the_param
Define what the parameter means. Don't leave it as is.

2023-12-25 15:34 UTC, literalEval commented on lib/views/after_auth_screens/add_post_page.dart
> +                    fontSize: 20,
Don't use constant sizing. Use SizeConfig instead.

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart
> +      builder: (BuildContext bc) {
Rename this to `context`.

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart
> +  void showImagePickerIcons(BuildContext context) {
If it is an ImagePicker Dialog, then why is it named showImagePickerIcons ?
Moreover, passing around contexts in functions is not the standard way to go about this. Please have a look at MVVM architecture once.

2023-12-25 15:34 UTC, literalEval commented on lib/view_model/after_auth_view_models/profile_view_models/edit_profile_view_model.dart
> +  Future<String> convertToBase64(File file) async {
You'll need to remove this in another PR once the ImageService one gets merged.

2023-12-25 19:40 UTC, Dante291 commented
@literalEval Sir I have resolved all the requested changes except the constant sizing one as constant sizing is being used for fontsize and icon size throughout the codebase, constant sizing makes more sense here as sizeConfig utilizes a dynamic approach by comparing with the entire screen resolution, so user had to try number of times in this case, do correct me if I'm wrong here.

other than that, I have used sizeConfig for sizing for all widgets and all.

2023-12-26 04:21 UTC, literalEval commented
@Dante291 fix the failing checks. Refactor the code wherever necessary.

2023-12-26 04:32 UTC, Dante291 commented
> @Dante291 fix the failing checks. Refactor the code wherever necessary.

Sir as suggested by you to follow MVVM architecture, I moved the code for modal sheet in the view file but due to this limit of 300 lines of code is exceeded, as view files contain whole UI logic of the screen there shouldnt be limit for view files, profile_page.dart file also has like 500+ lines so this check could be ignored here too.

2023-12-26 09:03 UTC, Dante291 commented
@literalEval please review sir.

2023-12-26 12:51 UTC, literalEval requested changes

2023-12-26 12:51 UTC, literalEval commented on lib/views/after_auth_screens/profile/edit_profile_page.dart
> +      BuildContext context, IconData icon, String label, VoidCallback onTap) {
Add a trailing comma and reformat.

2023-12-26 12:51 UTC, literalEval commented on lib/views/after_auth_screens/profile/edit_profile_page.dart
> +          Icon(icon, size: SizeConfig.screenHeight! * 0.05),
Add trailing comma and reformat lines 304 and 305.

2023-12-26 14:29 UTC, literalEval requested changes

2023-12-26 14:29 UTC, literalEval commented on lib/views/after_auth_screens/profile/profile_page.dart
> +                        height: 150,
Use SizeConfig.

2023-12-26 14:29 UTC, literalEval commented on lib/views/after_auth_screens/profile/profile_page.dart
> +                                key: const Key('inv1'),
Use a better key name.

2023-12-26 14:30 UTC, literalEval commented
@Dante291 use SizeConfig everywhere. Similarly, add trailing commas wherever needed and refactor.

2023-12-26 15:24 UTC, Dante291 commented
@literalEval properly formatted and used dynamic sizing wherever possible, please review sir.

2023-12-27 02:29 UTC, literalEval requested changes
Cover the uncovered lines in tests. Use codecov to find out the missing lines.

2023-12-27 02:38 UTC, Dante291 commented
> ## [Codecov](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2268?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> All modified and coverable lines are covered by tests ✅
> 
> > Comparison is base [(`c902baa`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa/commit/c902baaf1467b985b5301a6b30a06d92516e4956?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 88.27% compared to head [(`a459cb5`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2268?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 90.08%.
> > Report is 4 commits behind head on develop.
> 
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2268?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation).

@literalEval All lines covered sir

2023-12-27 03:15 UTC, literalEval approved these changes
LGTM

2023-12-27 04:46 UTC, palisadoes approved these changes

2023-12-27 04:46 UTC, merged