Main Screen View Model Tests Written
PalisadoesFoundation/talawa pull request #2278
Opened 2023-12-28 09:59 UTC by Manik2708

**What kind of change does this PR introduce?**
1) Improved the code coverage of the `MainScreenViewModel.dart`
2) Added multiple tests to improve the effectiveness of tests
3) Some of tests were not matching/expecting anything, improved those tests.

**Issue Number:**

Fixes #1121

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-30 16:12 UTC, Manik2708 commented on test/view_model_tests/main_screen_view_model_test.dart
> +      final app = MaterialApp(
I have made the changes. Please Review!

2024-01-02 15:14 UTC, literalEval commented on lib/view_model/main_screen_view_model.dart
> +  void tourHomeTargets([UserConfig? givenUserConfig]) {
I understand the rationale, but mocking will be a better way to go. Please look into mocking with mockito.

2024-01-02 15:15 UTC, literalEval requested changes

2024-01-02 15:15 UTC, literalEval commented on test/view_model_tests/main_screen_view_model_test.dart
> +Widget getMockApp(FunctionType onTap) {
1. Add a new line here.
2. Rename the function to be consistent with the naming used in other tests.

2024-01-02 15:53 UTC, Manik2708 commented on lib/view_model/main_screen_view_model.dart
> +  void tourHomeTargets([UserConfig? givenUserConfig]) {
> I understand the rationale, but mocking will be a better way to go. Please look into mocking with mockito.

So is there a way, to achieve this without injecting the mock model? I looked on other tests but found nothing to control the behaviour of UserConfig model when used inside a function. I am always doubtful of injecting dependency in this way, so would be very thankful if you can assist me!

2024-01-06 18:35 UTC, noman2002 commented
@Manik2708 Any update on this?

2024-01-06 23:47 UTC, Manik2708 commented
> @Manik2708 Any update on this?

There was some medical emergency at my home. Will update the PR till Monday.

2024-01-07 04:35 UTC, palisadoes commented
I hope all is well with you and your family that the recovery is speedy

2024-01-08 10:45 UTC, Manik2708 commented
> I hope all is well with you and your family that the recovery is speedy

All is fine now! Thanks a lot for your wishes @palisadoes.

2024-01-08 10:53 UTC, closed without merging

2024-01-08 16:07 UTC, palisadoes commented
1. Why was this closed? I've noticed that there is a trend to do this recently without explanation.
2. It is a real burden for us to keep assigning reviewers only to have their work discarded with this type of action
3. Please be respectful of our developers time

2024-01-08 16:20 UTC, Manik2708 commented
> 1. Why was this closed? I've noticed that there is a trend to do this recently without explanation.
> 2. It is a real burden for us to keep assigning reviewers only to have their work discarded with this type of action
> 3. Please be respectful of our developers time

I am so sorry for this, actually I updated the PR after installation of some dependencies leading to high number of conflicts. I will keep in mind to state reason next time before closing and before that I will try not to close it.