Bug: no validation and confirmation on comments
PalisadoesFoundation/talawa pull request #2349
Opened 2024-01-22 17:47 UTC by Dante291

**What kind of change does this PR introduce?**

This PR introduces an enhancement by implementing validation and confirmation mechanisms for comments.

**Issue Number:**

Fixes #2277 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[
[validation.webm](https://github.com/PalisadoesFoundation/talawa/assets/103507835/0dc78c15-c114-4531-a51b-a0e89fb0a70f)
](url)

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2024-01-23 03:36 UTC, Cioppolo14 commented
Please fix the failing tests.

2024-01-23 16:39 UTC, Dante291 commented
@palisadoes @Cioppolo14 please assign reviewers.

2024-01-24 00:40 UTC, Cioppolo14 commented
@literalEval @anwersayeed Can you review this PR?

2024-01-26 06:03 UTC, Dante291 commented
@noman2002 @literalEval please review this

2024-01-26 19:40 UTC, literalEval requested changes

2024-01-26 19:40 UTC, literalEval commented on lib/views/after_auth_screens/feed/individual_post.dart
> +              ///check if button is enabled when comment is valid
Use `//` for comments.

2024-01-26 19:40 UTC, literalEval commented on lib/views/after_auth_screens/feed/individual_post.dart
>      padding: const EdgeInsets.symmetric(vertical: 8.0),
Use dynamic sizing instead.

2024-01-26 19:40 UTC, literalEval commented on lib/views/after_auth_screens/feed/individual_post.dart
> +  /// List of user who liked the post.
*users

2024-01-26 19:40 UTC, literalEval commented on lib/views/after_auth_screens/feed/individual_post.dart
> +  /// LIst of comments on a post.
*List

2024-01-26 19:40 UTC, literalEval commented on lib/views/after_auth_screens/feed/individual_post.dart
> +/// * `Widget`: returns the circle avatar of the likedBy user who liked the post
Don't use words like returns, takes etc. It is obvious. Moreover, make the comment multi-line if the single line goes too wide.

2024-01-26 19:50 UTC, Dante291 commented
@literalEval made requested changes

2024-01-27 10:18 UTC, literalEval requested changes
There are some guidelines which you should try on enforcing yourself, like:

1. Writing better comments.
2. Adding trailing commas and refactoring.
3. Adding proper spacing on comments and docs.

2024-01-27 11:41 UTC, Dante291 commented
@literalEval 

1. I have revisited and have added more meaningful docs in the code to provide better clarity.
2.I have added trailing commas wherever necessary for proper readability of code.
3. Added proper spacing on comments and docs.

If, after these updates, there are still areas that require improvement, please feel free to specify the errors or provide additional guidance. Your feedback is highly valued, and I'm committed to delivering code that meets the highest standards.

2024-01-27 22:01 UTC, noman2002 approved these changes
LGTM

2024-01-27 22:20 UTC, palisadoes approved these changes

2024-01-27 22:20 UTC, merged