Created Session Management.
PalisadoesFoundation/talawa pull request #2362
Opened 2024-01-30 15:25 UTC by Azad99-9

**What kind of change does this PR introduce?**

This PR 

1. Introduces a new efficient Session Management System. 
2. Fixes the App crashes at multiple situations.

**Issue Number:**

Fixes #2356 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

`Session Management Feature:`
Implemented a new `SessionManager` Class.
**Functionalities**:
1. Creates a User session as soon as the app launches.
2. Refreshes the refresh token at a regular interval, with a refresh duration of 10 min.
**advantages**:
1. Reduces the overhead of refreshing the refresh token prior to every api call.
2. Prevents app from crashing at multiple situations.

`Fixed App Crashes:`
Prior to this PR the Talawa app was prone to app crash in following situations:
1. Switching organisations.
2. Post login.
3. Post signup,
4. When app is put to rebuild in debug mode.
- All the above situations caused developers to reinstall the app every time they encounter an app crash.
     
All the above mentioned scenarios of app crashes were fixed in this PR.

**Does this PR introduce a breaking change?**

No

**Other information**

Created a new file `lib/service/session_manager.dart`

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2024-01-30 16:15 UTC, Azad99-9 commented
- Unauthorized file test failed because added a new package `fake_async.`
- Required for testing async methods that run asynchronously at `regular intervals`.

2024-01-30 16:24 UTC, Azad99-9 commented
@Cioppolo14 @noman2002 please assign reviewers for this PR.

2024-01-31 01:11 UTC, Cioppolo14 commented
@noman2002 @literalEval Can you review this PR?

2024-01-31 16:30 UTC, Dante291 commented
@Azad99-9 would this also solve the app crashing issue when user switch to other org, I am facing this frequently now

2024-01-31 16:31 UTC, Azad99-9 commented
Yes @Dante291 it covers all the situations of app crash that we are facing right now.

2024-01-31 16:32 UTC, Azad99-9 commented
From now on we need not to reinstall the app everytime we try to rebuild it.

2024-01-31 16:39 UTC, Dante291 commented
> From now on we need not to reinstall the app everytime we try to rebuild it.

wait but thats not likely 

> From now on we need not to reinstall the app everytime we try to rebuild it.

wait so like after this fix we need to reinstall the app every time we try to rebuild it? wouldn't that affect development environment as developer has to reinstall every time in order to work on it? or did I get this wrong

2024-01-31 17:19 UTC, Azad99-9 commented
![Screenshot_20240116-001659](https://github.com/PalisadoesFoundation/talawa/assets/120930148/829b2b14-11b9-431e-bb6c-e3e6b8eb4253)

@Dante291 sorry you got me wrong, let me clear.

- The current app version we have on develop branch, crashes every time we try to rebuild it. As depicted in above image.
- This causes the devs to uninstall the app and reinstall it every time they face this crash, i guess you too have faced it? Making the developers work a bit hard.
- This PR has fixed aforementioned crash situation too.

2024-01-31 18:14 UTC, literalEval requested changes

2024-01-31 18:14 UTC, literalEval commented on lib/locator.dart
> +///creating GetIt for SessionManager.
Remove words like creating, returning etc.

2024-01-31 18:14 UTC, literalEval commented on lib/services/database_mutation_functions.dart
> +  /// initializes [clientNonAuth] function.
Capitalize first letter.

2024-01-31 18:14 UTC, literalEval commented on lib/splash_screen.dart
> +    final bool userLoggedIn = userConfig.loggedIn;
Cover this line in the tests.

2024-01-31 19:22 UTC, Dante291 commented
> ![Screenshot_20240131-225639](https://private-user-images.githubusercontent.com/120930148/301252757-99adfce1-8283-4600-b668-2cbe2f6cee5c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjkxMjAsIm5iZiI6MTcwNjcyODgyMCwicGF0aCI6Ii8xMjA5MzAxNDgvMzAxMjUyNzU3LTk5YWRmY2UxLTgyODMtNDYwMC1iNjY4LTJjYmUyZjZjZWU1Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxOTIwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDljZDQ1MDNkMzc0OGI0N2I1MDMxZmZjNjBhZmIxMTM3OGYyNzA4MDQyYWJiYjBmNjg0Yzk0YTI0YzJjZThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YJ2WnWaqbraX4MY63uRjMqPABC_wJjyd3p8K2XtxJAM)
> 
> @Dante291 sorry you got me wrong, let me clear.
> 
> * The current app version we have on develop branch, crashes every time we try to rebuild it. As depicted in above image.
> * This causes the devs to uninstall the app and reinstall it every time they face this crash, i guess you too have faced it? Making the developers work a bit hard.
> * This PR has fixed aforementioned crash situation too.

Oh ok got it, yeah this fix is really needed, Thanks.

2024-02-06 17:25 UTC, Azad99-9 commented
apologies for work delay, I was out of station for few days.

2024-02-06 17:27 UTC, Azad99-9 commented on pubspec.yaml
> +  uni_links_platform_interface: ^1.0.0
Added this line to mock platform interface in test environment.

2024-02-06 17:41 UTC, Azad99-9 commented
![Screenshot from 2024-02-06 23-10-15](https://github.com/PalisadoesFoundation/talawa/assets/120930148/ec736ef6-33e4-4a5c-bc4d-d004b9ff4733)

Even after covering the missing line the codecov is not being updated.

2024-02-06 17:42 UTC, Azad99-9 commented
> ## [Codecov](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2362?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> Attention: `1 lines` in your changes are missing coverage. Please review.
> 
> > Comparison is base [(`d46880b`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa/commit/d46880bad266539075c77b87d7d223d4d159b979?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 95.07% compared to head [(`6e26faf`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2362?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 95.07%.
> > Report is 5 commits behind head on develop.
> 
> > ❗ Current head [6e26faf](https://github.com/PalisadoesFoundation/talawa/commit/6e26faf61beb8ebb47aba25ca988b64d7a699eb4) differs from pull request most recent head [743b642](https://github.com/PalisadoesFoundation/talawa/commit/743b642dff52a8d4487a292264926ce673aaf0d3). Consider uploading reports for the commit [743b642](https://github.com/PalisadoesFoundation/talawa/commit/743b642dff52a8d4487a292264926ce673aaf0d3) to get more accurate results
> 
> [Files](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2362?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)	Patch %	Lines
> [lib/splash_screen.dart](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2362?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-bGliL3NwbGFzaF9zY3JlZW4uZGFydA==)	0.00%	[1 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2362?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/PalisadoesFoundation/talawa/pull/2362?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation).

![Screenshot from 2024-02-06 23-10-15](https://github.com/PalisadoesFoundation/talawa/assets/120930148/ec736ef6-33e4-4a5c-bc4d-d004b9ff4733)

Even after covering the missing line the codecov is not being updated.

2024-02-07 16:36 UTC, Azad99-9 commented
@literalEval please have a look at this PR.

2024-02-11 14:35 UTC, noman2002 approved these changes
Changes looks good to me. 
@Azad99-9 Good work.

2024-02-11 14:47 UTC, palisadoes approved these changes

2024-02-11 14:47 UTC, merged

2024-02-11 15:01 UTC, Azad99-9 commented
> Changes looks good to me. 
> @Azad99-9 Good work. 

Thank you for noticing my work @noman2002