Feature: Display Additional Organization and Address Data
PalisadoesFoundation/talawa pull request #2478
Opened 2024-04-16 19:49 UTC by Dante291

**What kind of change does this PR introduce?**

This PR introduces enhancements to the organization information display by providing additional details about the organization and its address

**Issue Number:**

Fixes #2354 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa/assets/103507835/c60d723d-fe44-4207-b689-de515f87382e

**If relevant, did you update the documentation?**

Yes

**Does this PR introduce a breaking change?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2024-04-16 20:28 UTC, Dante291 commented
@palisadoes @noman2002 org_info_screen.dart has more than 300 lines of code because it is a view file which contains UI logic so this can be ignored.

2024-04-16 20:42 UTC, palisadoes commented
Please add it to the appropriate section of the pull request GitHub action file and include it in this PR

2024-04-17 12:53 UTC, Dante291 commented
@palisadoes @noman2002 This is ready to be reviewed.

2024-04-17 13:40 UTC, palisadoes commented
Please get the code coverage for the patch. The lib/widgets/custom_list_tile.dart file needs more attention.

![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/8b7ed4b5-3ec3-40c1-95d2-38baf7f4716f)

![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/59c92b0f-ed74-489b-bff2-06ad450c672f)

2024-04-17 13:49 UTC, Dante291 commented
Yup working on it.

2024-04-17 16:42 UTC, Dante291 commented
@palisadoes CodeCov report didn't update...

2024-04-17 19:01 UTC, palisadoes requested changes
Please see comment

2024-04-17 19:01 UTC, palisadoes commented on assets/images/talawaorg.png
Why is was this file added?

2024-04-17 19:04 UTC, Dante291 commented on assets/images/talawaorg.png
I have added a default picture for an Organization if its null, I used this picture because it's in official design Figma file for Talawa.

2024-04-17 19:04 UTC, palisadoes commented on assets/images/talawaorg.png
The image should come from the API. If it's not available, the screen should not display an image.
It implies that the image will always be the same no matter the organization.

2024-04-17 19:05 UTC, palisadoes commented on assets/images/talawaorg.png
Please use a blank image

2024-04-17 19:11 UTC, Dante291 commented on assets/images/talawaorg.png
So if there is no Org Image I should not display anything? I think we could have a default Org Image to show not this Image but any general Image like this: 

![image](https://github.com/PalisadoesFoundation/talawa/assets/103507835/8533a2e5-d0ac-4f50-92a1-b6d1ef5fcb4b)

2024-04-17 19:37 UTC, palisadoes commented on assets/images/talawaorg.png
Use a single color image for the same reason mentioned before

2024-04-17 20:12 UTC, Dante291 commented on assets/images/talawaorg.png
Please let me know if this image is okay? It's a basic image  
[orgInfo2.webm](https://github.com/PalisadoesFoundation/talawa/assets/103507835/2400a22e-3f41-4349-ad05-7fd08e98b08b)

2024-04-17 20:13 UTC, Dante291 commented on assets/images/talawaorg.png
Is this Image ok? @palisadoes 

[orgInfo2.webm](https://github.com/PalisadoesFoundation/talawa/assets/103507835/da4f6cec-599d-4b55-bfb3-1f7f493e6c69)

2024-04-17 20:21 UTC, palisadoes commented on assets/images/talawaorg.png
OK

2024-04-18 14:25 UTC, palisadoes approved these changes

2024-04-18 14:25 UTC, merged