Venue Management for Event Plugin (GSoC)
PalisadoesFoundation/talawa pull request #2527
Opened 2024-07-10 17:29 UTC by Dante291

**What kind of change does this PR introduce?**

This PR introduces a new feature for venue management within the event management application. It adds basic CRUD capabilities to manage venue information, including name, capacity, description, and image URL.

**Issue Number:**

Fixes #2522 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa/assets/103507835/22e75f9d-4bd8-4108-83d0-cc4a90850479

**If relevant, did you update the documentation?**

Yes

**Does this PR introduce a breaking change?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2024-07-10 17:31 UTC, Dante291 commented
@palisadoes Sorry for closing two PRs I mistakenly created them against main branch

2024-07-11 15:05 UTC, noman2002 requested changes
Please fix the failing tests.

2024-07-21 18:09 UTC, noman2002 requested changes

2024-07-21 18:09 UTC, noman2002 commented on lib/views/after_auth_screens/events/create_event_page.dart
> +                                      fit: BoxFit.cover,
Use Image.asset everywhere instead of Image(image:AssetImage)

2024-07-26 19:31 UTC, palisadoes commented
@noman2002 PTAL

2024-07-26 19:50 UTC, noman2002 approved these changes
LGTM

2024-07-26 20:21 UTC, merged