Like Button changes color on clicking
PalisadoesFoundation/talawa pull request #260
Opened 2021-03-14 14:03 UTC by yasharth291

**What kind of change does this PR introduce?**

enhancement

**Summary**

it is related to the issue #235. This PR allows the icon button to change its color from grey to blue on clicking and if clicked again it will again change its color.

2021-03-14 14:06 UTC, yasharth291 commented
@Sagar2366  please could you look into it. By tonight i am going to resolve the issue number #235

2021-03-15 05:43 UTC, Sagar2366 commented
@yasharth291, Add more functionality to this PR - 
1. Clicking on like button again should remove like for the newsfeed. 
2. Should increase/decrease count of likes if different users like/remove like from the posts
3. Even if there is single like for the newsfeed, show icon in blue.

Also, additionally change the PR title consider above suggestions and description, add snaps/video showing different behaviour before and after adding changes.

2021-03-15 06:14 UTC, yasharth291 commented
Sure i will add some more functionality in this PR and   make this PR resolve more issues

2021-03-15 18:39 UTC, yasharth291 commented
Could anyone review it

2021-03-15 19:12 UTC, yasharth291 commented
The requirement asked for this PR are successfully Completed.

2021-03-16 03:55 UTC, jordanliu requested changes

2021-03-16 03:55 UTC, jordanliu commented on lib/views/pages/newsfeed/newsfeed.dart
> +  Map<String,bool> mp;
Unused variable

2021-03-16 03:55 UTC, jordanliu commented on lib/views/pages/newsfeed/newsfeed.dart
> +  bool like = false;
Unused variable

2021-03-16 06:24 UTC, yasharth291 commented on lib/views/pages/newsfeed/newsfeed.dart
> +  Map<String,bool> mp;
resolved

2021-03-16 11:16 UTC, yasharth291 commented
@jordanliu changes has been done please now can it be merged

2021-03-16 11:52 UTC, Sagar2366 approved these changes

2021-03-17 11:26 UTC, yasharth291 commented
Closing this and opening new with new changes

2021-03-17 11:26 UTC, closed without merging