Feat: Fundraising Campaigns (GSoC)
PalisadoesFoundation/talawa pull request #2635
Opened 2024-11-04 11:33 UTC by Dante291

**What kind of change does this PR introduce?**

Adds supports for fund raising campaigns in Talawa mobile app

**Issue Number:**

Fixes #2593 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/user-attachments/assets/10343d46-2cb0-43ab-8a5a-78a0fc014ba3

**If relevant, did you update the documentation?**

Yes

**Summary**

**Does this PR introduce a breaking change?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

Yes

2024-11-05 03:32 UTC, noman2002 requested changes
Do the suggested changes by coderabbit.

2024-11-10 20:49 UTC, palisadoes commented
Please fix the failing tests.

2024-11-19 07:29 UTC, noman2002 commented
@Dante291 I am approving this but create issue for each file of this project which has missing test cases.

2024-11-19 07:29 UTC, noman2002 approved these changes

2024-11-20 03:20 UTC, merged