Initial draft for PR Guidelines
PalisadoesFoundation/talawa pull request #328
Opened 2021-03-15 15:26 UTC by Sagar2366

Signed-off-by: Sagar Utekar <sagarutekar2366@gmail.com>

Summary :
This PR is added with initial draft for PR guidelines to follow.

2021-03-15 15:55 UTC, palisadoes commented
These are good general guidelines. 

We should have a GSoC specific section that:

1. Outlines how new issues get created (At the moment we are saying that students cannot open them, but they may have good ideas that should be an issue) It implies that a mentor should be involved, we just need to explain how this is done.
2. Adds the line or something similar "If you are borrowing code, please disclose it. It is fine and sometimes even recommended to borrow code, but we need to know about it to assess your work. If we find out that your pull request contains a lot of code copied from elsewhere, we will close the pull request."

2021-03-15 16:26 UTC, jordanliu commented
Hey @Sagar2366, could you also implement the following issue & pr templates in this PR as well: #293 - I think having a comment in the PR to read the guides would be helpful

2021-03-15 16:53 UTC, Sagar2366 commented
Sure @jordanliu, I'll add templates for issue and pr and other necessary details.

2021-03-15 17:00 UTC, jordanliu requested changes

2021-03-15 20:57 UTC, palisadoes commented on PR-guidelines.md
> +3. Each contributor may only create one pull request at a time. We have this rule in place due to our limited resources - if everyone was allowed to post multiple pull requests we will not be able to
It's unlikely that someone will need to work on multiple PRs. If they are, then at least one PR is suffering in code quality. I vote for keeping it.

2021-03-16 00:48 UTC, jordanliu commented on PR-guidelines.md
> +3. Each contributor may only create one pull request at a time. We have this rule in place due to our limited resources - if everyone was allowed to post multiple pull requests we will not be able to
@heyjordn what do you think?

2021-03-16 03:07 UTC, palisadoes commented on PR-guidelines.md
> +3. Each contributor may only create one pull request at a time. We have this rule in place due to our limited resources - if everyone was allowed to post multiple pull requests we will not be able to
Also, someone could hold things up by having multiple PRs that they forget about.

2021-03-16 03:40 UTC, jordanliu commented on PR-guidelines.md
> +3. Each contributor may only create one pull request at a time. We have this rule in place due to our limited resources - if everyone was allowed to post multiple pull requests we will not be able to
Fair point

2021-03-16 15:24 UTC, jordanliu approved these changes

2021-03-16 15:26 UTC, merged