[Fix] Membership requests are not being displayed on the Accept Membership Requests page
PalisadoesFoundation/talawa pull request #564
Opened 2021-03-30 17:06 UTC by Raunakk02

**What kind of change does this PR introduce?**
[bugfix] Membership requests are now being displayed on the Accept Membership Requests page which was not displayed previously.

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
No

**Summary**
Resolves #563 

**Does this PR introduce a breaking change?**
No

2021-03-30 17:48 UTC, Sagar2366 commented
@Raunakk02 add problem and solution video.
Also, CI is failing please check.

2021-04-01 17:14 UTC, Sagar2366 requested changes
> @Sagar2366 I have merged the recent changes from upstream/master.

add problem and solution video.
Disable code-autoformatter so that only changes you added will get added to commit. Once done, send PR again for review.

2021-04-01 17:21 UTC, Raunakk02 commented on lib/views/pages/organization/accept_requests_page.dart
> +    QueryResult result = await _client
Sure, working on it!

2021-04-01 17:21 UTC, Raunakk02 commented on lib/views/pages/organization/accept_requests_page.dart
> +    QueryResult result = await _client
Sure, working on it!

2021-04-01 17:51 UTC, Raunakk02 commented
@Sagar2366 I have changed the code which you marked back to the original format and also disabled the code auto-formatter before doing so. 
Awaiting review!

2021-04-03 06:28 UTC, Sagar2366 approved these changes

2021-04-03 06:28 UTC, merged