GSoC branch lang controller addition
PalisadoesFoundation/talawa pull request #897
Opened 2021-06-19 14:56 UTC by sumitra19jha

**What kind of change does this PR introduce?**
Ability to update/change language through controller

**Issue Number:**

Fixes #798 
Fixes #800 before auth
Fixes #801 

**Did you add tests for your changes?**
No, Seprate issue exists for that

**Snapshots/Videos:**

https://user-images.githubusercontent.com/35868598/122646387-7bc9d580-d13c-11eb-9f0b-3b2ffe1294af.mp4

**If relevant, did you update the documentation?**
Not needed here

**Summary**
Develop branch language update 

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md)?**

2021-06-22 13:01 UTC, DeltaHarbinger commented
Hey @sumitra19jha, some of the tests are failing on this PR. Is there something that needs to be changed with your code or with the pipelines?

2021-06-22 13:03 UTC, sumitra19jha commented
Yeah, I am working bon them. It is related to a notifier problem.

2021-06-22 13:47 UTC, DeltaHarbinger commented
Alright, thanks for the update

2021-06-22 16:05 UTC, CyberWake commented
@sumitra19jha can you please look in to the thing like in verify text in some languages goes to 2 line plus the greeting text in english and french come as intended but in Chinese and hindi it doesn't

2021-06-22 16:06 UTC, sumitra19jha commented
@CyberWake Ok. Working on improving that

2021-06-22 16:21 UTC, sumitra19jha commented
@DeltaHarbinger During the language conversion the context is very important, which is given by the full sentence. In the case of Hindi and Chinese the meaning actually gets affected if we ended up breaking it like english. So full sentence is taken as a reference. 

The problem here is also the widget. While designing the UI, we focused on single language and then widgets are implemented accordingly (for the case of greeting the use of Rich Text). So the JSON are made like that.

### For English
![Screenshot 2021-06-22 at 9 49 41 PM](https://user-images.githubusercontent.com/35868598/122963434-e29cf800-d3a3-11eb-98d8-64ae7f508fb2.png)

## For Hindi
![Screenshot 2021-06-22 at 9 49 56 PM](https://user-images.githubusercontent.com/35868598/122963445-e4ff5200-d3a3-11eb-8b29-801162825da0.png)

## For Spanish
![Screenshot 2021-06-22 at 9 50 09 PM](https://user-images.githubusercontent.com/35868598/122963451-e597e880-d3a3-11eb-88b6-416b17ab9dff.png)

## For Chinese
![Screenshot 2021-06-22 at 9 50 17 PM](https://user-images.githubusercontent.com/35868598/122963453-e6307f00-d3a3-11eb-92fa-11e399fac978.png)

2021-06-22 16:27 UTC, sumitra19jha commented
There is one issue in this PR which is causing error during signup so I have marked it as a draft. I will fix this as soon as possible.

2021-06-22 20:26 UTC, sumitra19jha commented
@DeltaHarbinger @CyberWake @dellyjm @Sagar2366 @rutvik11062000 @utkarshshendge Please Review the PR

https://user-images.githubusercontent.com/35868598/122994103-b5614180-d3c5-11eb-8843-86142c6f0ef4.mp4

2021-06-23 12:59 UTC, sumitra19jha commented
The PR is ready to be merged

2021-06-23 17:25 UTC, CyberWake commented
> @DeltaHarbinger @CyberWake @dellyjm @Sagar2366 @rutvik11062000 @utkarshshendge Please Review the PR
> 
>  WhatsApp.Video.2021-06-23.at.1.51.22.AM.mp4

I feel like having the languages on the language page itself in the same locale would we much better, this is just the input what other social/management apps do.

2021-06-23 17:26 UTC, CyberWake commented
Please look into the test as well they are failing.

2021-06-23 17:28 UTC, sumitra19jha commented
@CyberWake Travis CI is passing

2021-06-23 18:27 UTC, CyberWake commented
> @CyberWake Travis CI is passing. Can you point out which test cases are failing?

Try running locally you'll get to know if it's not clear with the logs over here.

2021-06-23 19:34 UTC, sumitra19jha commented
@CyberWake Can you attach the snapshot of which test failed locally?

2021-06-23 20:03 UTC, sumitra19jha commented
@CyberWake Locally everything is working fine on my system!!!

2021-06-23 21:36 UTC, CyberWake commented
> @CyberWake Locally everything is working fine on my system!!!

did you really check it?

2021-06-23 21:42 UTC, CyberWake commented
> @CyberWake Locally everything is working fine on my system!!!

did you check it? like from logs itself I see the test are failing in ```select_language_page_test.dart``` file. And error would also be thrown irrespective of machine its running on please cross check again.

2021-06-24 03:33 UTC, sumitra19jha commented
@CyberWake Please share your error log screenshot. I am not able to see any on my local system.

This is the screenshot of `select_language_page_test.dart test` on my local system.
![Screenshot 2021-06-24 at 9 00 01 AM](https://user-images.githubusercontent.com/35868598/123198547-ee370e80-d4ca-11eb-8f7c-5122612d5e56.png)

2021-06-24 06:55 UTC, CyberWake commented
> @CyberWake Please share your error log screenshot. I am not able to see any on my local system.
> 
> This is the screenshot of `select_language_page_test.dart test` on my local system.
> ![Screenshot 2021-06-24 at 9 00 01 AM](https://user-images.githubusercontent.com/35868598/123198547-ee370e80-d4ca-11eb-8f7c-5122612d5e56.png)

please look into the line 5 widgets with key and for more please run the test in android studio if possible.

2021-06-24 07:39 UTC, sumitra19jha commented
@CyberWake There is no issue with line 5. This is appearing because of print statement, as we have added same key to more than 1 items. If you are facing any issue, Please message me on slack with screenshot and we will work on that.

https://user-images.githubusercontent.com/35868598/123221351-7d085300-d4ec-11eb-91dc-1646c8df20e5.mov

.

2021-06-24 09:16 UTC, CyberWake commented
> @CyberWake There is no issue with line 5. This is appearing because of print statement, as we have added same key to more than 1 items. If you are facing any issue, Please message me on slack with screenshot and we will work on that.
> 
>  screen-recording-2021-06-24-at-125726-pm_iUMuOMvi.mov 
> .

please run the test in android studio the full statement is not shown here i would recommend you to use android studio to run test there you get better logs. and the exact log could itself be seen from the workflow adding for convenience
```The following TestFailure object was thrown running a test:
  Expected: BoxDecoration:<BoxDecoration(color: Color(0x00000000))>
  Actual: BoxDecoration:<BoxDecoration(color: Color(0x26c4c4c4))>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/runner/work/talawa/talawa/test/widget_tests/select_language_page_test.dart:235:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

This was caught by the test expectation on the following line:
  file:///home/runner/work/talawa/talawa/test/widget_tests/select_language_page_test.dart line 235
The test description was:
  Testing to change language items
```

2021-06-24 12:27 UTC, sumitra19jha commented
@CyberWake This is happening because the `async` request on your system is running slow. I will fix this in next commit.

I am inclined to work for both frontend and backend so I am more comfortable with VS Code then Android Studio. For testing purposes it works very fine.

2021-06-24 19:31 UTC, CyberWake commented
> @CyberWake This is happening because the `async` request on your system is running slow. I will fix this in next commit.
> 
> I work on both frontend and backend so I am more comfortable with VS Code then Android Studio. For both development and testing purposes it works very fine.

can you please run the test in android studio it is not something dependent on machine

2021-06-25 20:36 UTC, sumitra19jha commented
@DeltaHarbinger @CyberWake @dellyjm @rutvik11062000 @utkarshshendge @Sagar2366 
Please review the PR its ready

2021-06-25 20:41 UTC, CyberWake commented
> @DeltaHarbinger @CyberWake @dellyjm @rutvik11062000 @utkarshshendge @Sagar2366
> Please review the PR its ready

please look up on the review comments

2021-06-25 20:41 UTC, sumitra19jha commented
What review comments? @CyberWake

2021-06-25 20:42 UTC, sumitra19jha commented
Is there any issue in these changes? @CyberWake

2021-06-25 20:43 UTC, CyberWake requested changes

2021-06-25 20:44 UTC, sumitra19jha commented on lib/views/pre_auth_screens/select_language.dart
> +            // const CupertinoSearchTextField(
This is not required right now. This is the reason I removed it, moreover why are you using CupertinoSearchTextField when major use base is for android

2021-06-25 20:44 UTC, CyberWake commented
sorry i forgot to submit my review 😥

2021-06-25 20:46 UTC, sumitra19jha commented on lib/views/pre_auth_screens/select_language.dart
> +            // const CupertinoSearchTextField(
If more than 10 languages will be added then I will make sure to implement search (but still I wouldn't recommend to use CupertinoSearchTextField in that case too)

2021-06-28 22:47 UTC, sumitra19jha commented on lib/router.dart
> -      final int selectedLangId = int.parse(settings.arguments!.toString());
it will not work due to lack of json files, for languages currently. But, this will be done in July though.

2021-06-28 23:00 UTC, sumitra19jha commented
@CyberWake @rutvik11062000 @utkarshshendge @DMills27 @palisadoes Please review

2021-06-28 23:01 UTC, palisadoes approved these changes

2021-06-28 23:01 UTC, merged